## Curso NumPy  - Aula 06 - Vetores 3D

Intrutor: Rafael F.V.C. Santos

Canal YouTube: https://bit.ly/CanalYouTube-Analistas-Quant 

Curso Python Fundamentos (Grátis): http://bit.ly/python-fundamentos

In [ ]:
import numpy as np

In [ ]:
# Exemplo de um vetor 3D

In [ ]:
v3 = np.array([ [ [1,2],[3,4],[5,6],[7,8] ] ])

In [ ]:
v3

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [ ]:
v3.shape

(1, 4, 2)

In [ ]:
v4 = np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] ])

In [ ]:
v4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
v4.shape

(2, 2, 2)

In [ ]:
# Reshape - Array 3D

In [ ]:
a1 = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

In [ ]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a2 = a1.reshape(3,2,2)

In [ ]:
a2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
a4 = a1.reshape(3,1,4)

In [ ]:
a4

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [ ]:
# Slicing Array 3D

In [ ]:
m1 = np.array([[[7, 8, 5], [5, 2, 4], [17, 5, 8]],
                [[6, 7, 1], [4, 1, 1], [6, 2, 1]],
                [[5, 1, 0], [72, 9, 3], [7, 9, 5]]])

In [ ]:
m1

array([[[ 7,  8,  5],
        [ 5,  2,  4],
        [17,  5,  8]],

       [[ 6,  7,  1],
        [ 4,  1,  1],
        [ 6,  2,  1]],

       [[ 5,  1,  0],
        [72,  9,  3],
        [ 7,  9,  5]]])

In [ ]:
m1_n = m1[:2, 1:,:1]

In [ ]:
m1_n

array([[[ 5],
        [17]],

       [[ 4],
        [ 6]]])

In [ ]:
m1_n2 = m1[2,:,:]

In [ ]:
m1_n2

array([[ 5,  1,  0],
       [72,  9,  3],
       [ 7,  9,  5]])

In [ ]:
m1[-1,:,:]    # start:end:step

array([[ 5,  1,  0],
       [72,  9,  3],
       [ 7,  9,  5]])

In [ ]:
# Transformar Array 3D para 2D

In [ ]:
g1 = np.array([[[1, 9],
        [1, 2]],

       [[1, 2],
        [1, 9]],

       [[4,  3],
        [1,  3]],

       [[2,  5],
        [6, 2]]])

In [ ]:
g1.shape

(4, 2, 2)

In [ ]:
g2 = np.reshape(g1, (4,4))

In [ ]:
g2

array([[1, 9, 1, 2],
       [1, 2, 1, 9],
       [4, 3, 1, 3],
       [2, 5, 6, 2]])

In [ ]:
np.reshape(g2, (4, 2, 2))

array([[[1, 9],
        [1, 2]],

       [[1, 2],
        [1, 9]],

       [[4, 3],
        [1, 3]],

       [[2, 5],
        [6, 2]]])

In [ ]:
g2.reshape((4, 2, 2))

array([[[1, 9],
        [1, 2]],

       [[1, 2],
        [1, 9]],

       [[4, 3],
        [1, 3]],

       [[2, 5],
        [6, 2]]])

In [ ]:
# Transposta de uma Vetor 3D

In [ ]:
vet = np.array([[[7, 8, 5], [5, 2, 4], [17, 5, 8]],
                [[6, 7, 1], [4, 1, 1], [6, 2, 1]],
                [[5, 1, 0], [72, 9, 3], [7, 9, 5]]])

In [ ]:
vet

array([[[ 7,  8,  5],
        [ 5,  2,  4],
        [17,  5,  8]],

       [[ 6,  7,  1],
        [ 4,  1,  1],
        [ 6,  2,  1]],

       [[ 5,  1,  0],
        [72,  9,  3],
        [ 7,  9,  5]]])

In [ ]:
vet.transpose()

array([[[ 7,  6,  5],
        [ 5,  4, 72],
        [17,  6,  7]],

       [[ 8,  7,  1],
        [ 2,  1,  9],
        [ 5,  2,  9]],

       [[ 5,  1,  0],
        [ 4,  1,  3],
        [ 8,  1,  5]]])

In [ ]:
vet.T

array([[[ 7,  6,  5],
        [ 5,  4, 72],
        [17,  6,  7]],

       [[ 8,  7,  1],
        [ 2,  1,  9],
        [ 5,  2,  9]],

       [[ 5,  1,  0],
        [ 4,  1,  3],
        [ 8,  1,  5]]])

In [ ]:
vet[0].T

array([[ 7,  5, 17],
       [ 8,  2,  5],
       [ 5,  4,  8]])

In [ ]:
vet[0,:,:].T

array([[ 7,  5, 17],
       [ 8,  2,  5],
       [ 5,  4,  8]])

In [ ]:
vet[1,:,:].T

array([[6, 4, 6],
       [7, 1, 2],
       [1, 1, 1]])

In [ ]:
# Somar elementos de Vetor 3D

In [ ]:
vet2 = np.array([[[1, 1, 0], [2, 2, 2], [3, 2, 3]],
                [[1, 0, 3], [2, 1, 2], [2, -1, 2]],
                [[2, 1, 2], [1, 0, 1], [1, 0, 1]]])

In [ ]:
vet2

array([[[ 1,  1,  0],
        [ 2,  2,  2],
        [ 3,  2,  3]],

       [[ 1,  0,  3],
        [ 2,  1,  2],
        [ 2, -1,  2]],

       [[ 2,  1,  2],
        [ 1,  0,  1],
        [ 1,  0,  1]]])

In [ ]:
np.sum(vet2, axis=1)

array([[6, 5, 5],
       [5, 0, 7],
       [4, 1, 4]])

In [ ]:
np.sum(vet2)

37

In [ ]:
np.sum(vet2, axis=0)

array([[4, 2, 5],
       [5, 3, 5],
       [6, 1, 6]])

In [ ]:
# Estatísticas descritivas Vetor 3D

In [ ]:
# Min, Max, Mean, Std

In [ ]:
vet2

array([[[ 1,  1,  0],
        [ 2,  2,  2],
        [ 3,  2,  3]],

       [[ 1,  0,  3],
        [ 2,  1,  2],
        [ 2, -1,  2]],

       [[ 2,  1,  2],
        [ 1,  0,  1],
        [ 1,  0,  1]]])

In [ ]:
np.min(vet2)

-1

In [ ]:
np.max(vet2)

3

In [ ]:
np.mean(vet2)

1.3703703703703705

In [ ]:
np.std(vet2)

0.9868824144054984

In [ ]:
np.min(vet2, axis=0)

array([[ 1,  0,  0],
       [ 1,  0,  1],
       [ 1, -1,  1]])

In [ ]:
np.min(vet2, axis=1)

array([[ 1,  1,  0],
       [ 1, -1,  2],
       [ 1,  0,  1]])

In [ ]:
# Funções ones, zeros, eye - vetores 3D

In [ ]:
x1 = np.ones( (3,4,3) )

In [ ]:
x1

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
x2 = np.zeros( (3,4,3) ); x2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
x3 = np.eye( (3,4,3) ); x3 # nao podemos utilizar assim 

TypeError: ignored

In [ ]:
np.eye( 4 )

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye( (3,4) ) # nao podemos utilizar assim 

TypeError: ignored

## Salvando em Arquivos os dados de Array

In [ ]:
a = np.array([1, 3, 5, 7])

In [ ]:
a2 = np.vander([1, 3, 5, 7],5)

In [ ]:
a2

array([[   1,    1,    1,    1,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [2401,  343,   49,    7,    1]])

In [ ]:
np.savetxt('Dados.txt', a, fmt='%d')

In [ ]:
np.savetxt('Dados2.txt', a2, fmt='%f')

In [ ]:
# Como abrir arquivos TXT

In [ ]:
u = np.loadtxt('Dados2.txt', dtype=float)

In [ ]:
u

array([[1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [8.100e+01, 2.700e+01, 9.000e+00, 3.000e+00, 1.000e+00],
       [6.250e+02, 1.250e+02, 2.500e+01, 5.000e+00, 1.000e+00],
       [2.401e+03, 3.430e+02, 4.900e+01, 7.000e+00, 1.000e+00]])

In [ ]:
# Para Exercício - Estudar:

arre.tofile()
np.fromfile()
np.save() # equivalente linguagem MatLab
np.load()

## Para continuar os estudos

In [ ]:
# Concatenação 
# Rotações
# Salvar dados 

In [ ]:
# Slicing Saltando Valores 1D

In [ ]:
m = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
m[0:10:3]  # start:end:step

array([ 1,  4,  7, 10])