## Curso NumPy  - Aula 03 - Sobre NaN , zeros nos Arrays 

Intrutor: Rafael F.V.C. Santos

Canal YouTube: https://bit.ly/CanalYouTube-Analistas-Quant 

Curso Python Fundamentos (Grátis): http://bit.ly/python-fundamentos

In [1]:
import numpy as np

### Ausência de Números

In [2]:
# NaN - Not a Number

x = np.array([1, 2, np.nan, 3, np.nan, 5])

In [3]:
x

array([ 1.,  2., nan,  3., nan,  5.])

In [7]:
x*2

array([ 2.,  4., nan,  6., nan, 10.])

In [4]:
x2 = np.array([1, 2, 'nan', 3, np.nan, 5])

In [5]:
x2

array(['1', '2', 'nan', '3', 'nan', '5'], dtype='<U32')

In [6]:
x2*2

UFuncTypeError: ignored

In [8]:
x3 = [1, 2, 'nan', 3, np.nan, 5]

In [9]:
x3

[1, 2, 'nan', 3, nan, 5]

### Removendo NaNs de Arrays

In [10]:
x4 = np.array([1, 2, np.nan, 3, np.nan, 5, np.nan, 2, 1, 5, 8, 9, np.nan, 11, 3, 2, 7, np.nan])

In [22]:
lista = []
for i in x4:
  if np.isnan(i):
    print('---> NaN')
  else:
    lista.append(i)
    print(i)

1.0
2.0
---> NaN
3.0
---> NaN
5.0
---> NaN
2.0
1.0
5.0
8.0
9.0
---> NaN
11.0
3.0
2.0
7.0
---> NaN


In [24]:
x5 = np.array(lista)

In [25]:
x5

array([ 1.,  2.,  3.,  5.,  2.,  1.,  5.,  8.,  9., 11.,  3.,  2.,  7.])

In [26]:
x6 = x4[~np.isnan(x4)]

In [27]:
x5

array([ 1.,  2.,  3.,  5.,  2.,  1.,  5.,  8.,  9., 11.,  3.,  2.,  7.])

### Operações em vetores com NaN

In [34]:
x4

array([ 1.,  2., nan,  3., nan,  5., nan,  2.,  1.,  5.,  8.,  9., nan,
       11.,  3.,  2.,  7., nan])

In [31]:
x4.sum()

nan

In [32]:
x4.mean()

nan

In [33]:
x4.std()

nan

In [35]:
# Remover NaN para poder executar as operações 

In [38]:
x4[~np.isnan(x4)].sum()

59.0

In [39]:
x4[~np.isnan(x4)].mean()

4.538461538461538

In [44]:
x4[~np.isnan(x4)].std()

3.1529079279875685

### Removendo elementos Nulos

In [46]:
y = np.array([1, 0, np.nan, 3, np.nan, 5, np.nan, 2, 1, 0, 8, 0, np.nan, 0, 3, 0, 7, np.nan])

In [49]:
y.nonzero()

(array([ 0,  2,  3,  4,  5,  6,  7,  8, 10, 12, 14, 16, 17]),)

In [48]:
type(y.nonzero())

tuple

In [50]:
ind = y.nonzero()

In [51]:
y[ind]

array([ 1., nan,  3., nan,  5., nan,  2.,  1.,  8., nan,  3.,  7., nan])

In [52]:
y[y.nonzero()]

array([ 1., nan,  3., nan,  5., nan,  2.,  1.,  8., nan,  3.,  7., nan])

In [54]:
y[ind][~np.isnan(y)]

IndexError: ignored

In [55]:
# Solução do Erro de Indexação

In [57]:
y[ind][]

array([ 1., nan,  3., nan,  5., nan,  2.,  1.,  8., nan,  3.,  7., nan])

In [58]:
y

array([ 1.,  0., nan,  3., nan,  5., nan,  2.,  1.,  0.,  8.,  0., nan,
        0.,  3.,  0.,  7., nan])

In [59]:
np.isnan(y)

array([False, False,  True, False,  True, False,  True, False, False,
       False, False, False,  True, False, False, False, False,  True])

In [60]:
np.isnan(y[ind])

array([False,  True, False,  True, False,  True, False, False, False,
        True, False, False,  True])

In [61]:
y[ind][~np.isnan(y[ind])]

array([1., 3., 5., 2., 1., 8., 3., 7.])

In [62]:
y_sem_zeros = y[y.nonzero()]

In [63]:
y_sem_zeros

array([ 1., nan,  3., nan,  5., nan,  2.,  1.,  8., nan,  3.,  7., nan])

In [64]:
y_sem_zeros_e_nan = y_sem_zeros[~np.isnan(y_sem_zeros)]

In [65]:
y_sem_zeros_e_nan

array([1., 3., 5., 2., 1., 8., 3., 7.])

## Modificando Elementos de um Array

In [66]:
# Funções fill(), flat, .clip()

In [94]:
h = np.array([-4,-3,-2,-1,0,1,2,3,4,5])

In [78]:
h

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [79]:
h.fill(9)

In [80]:
h

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [86]:
h.fill('Python')

ValueError: ignored

In [90]:
h.flat = 88

In [91]:
h

array([88, 88, 88, 88, 88, 88, 88, 88, 88, 88])

In [92]:
h.flat = 'Python'

ValueError: ignored

In [95]:
# Função .Clip()

In [103]:
h = np.array([-4,-3,-2,-1,0,1,2,3,4,5])

In [104]:
h

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [105]:
h.clip(-2,2)

array([-2, -2, -2, -1,  0,  1,  2,  2,  2,  2])

In [106]:
h.clip(-3,4)

array([-3, -3, -2, -1,  0,  1,  2,  3,  4,  4])

### Como ordenar elementos de um array

In [15]:
w = np.array([6,2,-4,8,1,-3,1,0,-2,6,-1,0,1,-2,3,-1,4,3,0,1,5])

In [16]:
w

array([ 6,  2, -4,  8,  1, -3,  1,  0, -2,  6, -1,  0,  1, -2,  3, -1,  4,
        3,  0,  1,  5])

In [30]:
w.sort()

In [31]:
w

array([-4, -3, -2, -2, -1, -1,  0,  0,  0,  1,  1,  1,  1,  2,  3,  3,  4,
        5,  6,  6,  8])

In [32]:
sorted(w,reverse=True)

[8, 6, 6, 5, 4, 3, 3, 2, 1, 1, 1, 1, 0, 0, 0, -1, -1, -2, -2, -3, -4]

In [33]:
w = sorted(w,reverse=True)

In [34]:
w

[8, 6, 6, 5, 4, 3, 3, 2, 1, 1, 1, 1, 0, 0, 0, -1, -1, -2, -2, -3, -4]

In [21]:
v = [4,2,8,1,2,9,2]

In [27]:
v.sort(reverse=True)

In [28]:
v

[9, 8, 4, 2, 2, 2, 1]

### Arrays especiais

In [ ]:
# Zeros, Empty, Ones

In [37]:
u = np.zeros(20)

In [38]:
u

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [39]:
v = np.empty(20)

In [40]:
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [41]:
type(u)

numpy.ndarray

In [42]:
type(v)

numpy.ndarray

In [44]:
u.dtype

dtype('float64')

In [45]:
v.dtype

dtype('float64')

In [46]:
z = np.ones(20)

In [47]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [48]:
# Validação da igualdade
u == v

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
# Métodos .repeat() e .full()

In [63]:
h = np.array([0])

In [64]:
h

array([0])

In [65]:
h.repeat(20)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
h2 = np.array([1])

In [67]:
h2

array([1])

In [68]:
h2.repeat(3)

array([1, 1, 1])

In [69]:
h3 = np.array([3.14])

h3.repeat(7)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [70]:
h8 = np.ones(7)

In [72]:
h8*3.14

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [ ]:
# Uso do método .full()

In [73]:
q = np.full((1,9),7)

In [75]:
q2 = np.ones(9)*7

In [76]:
q2

array([7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [74]:
q

array([[7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [77]:
q2.dtype

dtype('float64')

In [78]:
q.dtype

dtype('int64')

In [79]:
q3 = np.full((1,9),7.)

In [80]:
q3

array([[7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [82]:
q3.dtype

dtype('float64')

In [84]:
q3.shape

(1, 9)

In [85]:
q2.shape

(9,)

In [86]:
q4 = np.full((2,9),7.)

In [87]:
q4

array([[7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [ ]:
# Vetor arange()

In [109]:
a = np.arange(50,101)

In [110]:
a

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [112]:
a2 = np.arange(50,101,2)

In [114]:
a2

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [115]:
a3 = np.arange(50,101,4)

In [116]:
a3

array([50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94, 98])

In [118]:
(a3 + 1)*2/5

array([20.4, 22. , 23.6, 25.2, 26.8, 28.4, 30. , 31.6, 33.2, 34.8, 36.4,
       38. , 39.6])

### Array-List-Array

In [119]:
r = np.array([0.1,0.5,-0.4,0.2,0.7,-0.2])

In [120]:
r

array([ 0.1,  0.5, -0.4,  0.2,  0.7, -0.2])

In [121]:
list(r)

[0.1, 0.5, -0.4, 0.2, 0.7, -0.2]

In [122]:
r.tolist()

[0.1, 0.5, -0.4, 0.2, 0.7, -0.2]

In [123]:
r

array([ 0.1,  0.5, -0.4,  0.2,  0.7, -0.2])

In [124]:
# Para mudar a natureza do vetor 'r'
r = r.tolist()

In [125]:
r

[0.1, 0.5, -0.4, 0.2, 0.7, -0.2]

In [126]:
np.array(r)

array([ 0.1,  0.5, -0.4,  0.2,  0.7, -0.2])

In [127]:
np.asarray(r)

array([ 0.1,  0.5, -0.4,  0.2,  0.7, -0.2])

In [134]:
f = np.ones((3,4))

In [137]:
f1 = f.tolist()

In [138]:
np.asarray(f1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])