## Curso NumPy  - Aula 02

Intrutor: Rafael F.V.C. Santos

Canal YouTube: https://bit.ly/CanalYouTube-Analistas-Quant 

Curso Python Fundamentos (Grátis): http://bit.ly/python-fundamentos 

In [ ]:
import numpy as np

In [ ]:
## Array 1D

In [ ]:
x = np.array([])

In [ ]:
x

array([], dtype=float64)

In [ ]:
y = np.array([1,2,3,4])

In [ ]:
y

array([1, 2, 3, 4])

In [ ]:
# Array 1D:
y.shape

(4,)

In [ ]:
y.dtype

dtype('int64')

In [ ]:
# Transposta de um Array

In [ ]:
y

array([1, 2, 3, 4])

In [ ]:
y.T

array([1, 2, 3, 4])

In [ ]:
A = np.array([[1,2,3],[4,5,6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Tipos de Arrays no NumPy

In [ ]:
x1 = np.array([1,2,3,4], dtype=np.int32)
x2 = np.array([1,2,3,4], dtype=np.int64)     # padrão - default
x3 = np.array([1,2,3,4], dtype=np.float32)
x4 = np.array([1,2,3,4], dtype=np.float64)   # padrão - default
x5 = np.array([1,2,3,4], dtype=np.float128)
x6 = np.array([1,2,3,4], dtype=np.complex64)
x7 = np.array([1,2,3,4], dtype=np.complex128) # padrão - default
x8 = np.array([1,2,3,4], dtype=np.complex256)

In [ ]:
x1

array([1, 2, 3, 4], dtype=int32)

In [ ]:
x2

array([1, 2, 3, 4])

In [ ]:
x3

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
x4

array([1., 2., 3., 4.])

In [ ]:
x5

array([1., 2., 3., 4.], dtype=float128)

In [ ]:
x6

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

In [ ]:
x7

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
x8

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex256)

In [ ]:
# Como modificar os tipos

In [ ]:
x1

array([1, 2, 3, 4], dtype=int32)

In [ ]:
x1.dtype

dtype('int32')

In [ ]:
# modificando o tipo:
x1.astype(np.float128)

array([1., 2., 3., 4.], dtype=float128)

In [ ]:
x1

array([1, 2, 3, 4], dtype=int32)

In [ ]:
# Erro ao obter a dimensão de um vetor 1D

In [ ]:
x = np.array([1,2,3,4])

y = np.array([2.1,4.7,4.4])

In [ ]:
x

array([1, 2, 3, 4])

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y

array([2.1, 4.7, 4.4])

In [ ]:
y.dtype

dtype('float64')

In [ ]:
x.shape

(4,)

In [ ]:
x.shape[0]

4

In [ ]:
x.shape[1]

IndexError: ignored

In [ ]:
xd = np.array([[1,2,3],[4,5,6]])

In [ ]:
xd

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n,m = xd.shape

ValueError: ignored

In [ ]:
x.ndim

1

In [ ]:
xd.ndim

2

In [ ]:
x = np.array([[1,2,3],[4,5,6]])

x = np.array([2.1, 4.7, 4.4])

In [ ]:
if(x.ndim == 1):
  n = x.shape
else:
  n,m = x.shape

In [ ]:
m

3

## Indexing e Slicing

In [ ]:
x = np.array([1.2, 1.5, 3., 5.2, 7.7])

In [ ]:
x

array([1.2, 1.5, 3. , 5.2, 7.7])

In [ ]:
a = x[0]

b = x[-1]  # x[4]

In [ ]:
a

1.2

In [ ]:
b

7.7

In [ ]:
z = a+b

In [ ]:
z

8.9

In [ ]:
x[1:3]

array([1.5, 3. ])

In [ ]:
x[1:4]

array([1.5, 3. , 5.2])

In [ ]:
x[-2]

5.2

In [ ]:
x[-2:]

array([5.2, 7.7])

In [ ]:
t1 = x[2:3]

In [ ]:
t2 = x[2]

In [ ]:
type(t1)

numpy.ndarray

In [ ]:
type(t2)

numpy.float64

In [ ]:
t1

array([3.])

In [ ]:
t2

3.0

In [ ]:
t1+t2

array([6.])

In [ ]:
t1 == t2

array([ True])

In [ ]:
 u = t1 == t2

In [ ]:
u.dtype

dtype('bool')

In [ ]:
# Avaliações booleanas básicas

In [ ]:
x = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])
y = np.array([1. , 2.6 , 3., 4. , 7. , 5.6])

In [ ]:
x

array([1. , 3. , 2.6, 4.3, 7.7, 5.6])

In [ ]:
y

array([1. , 2.6, 3. , 4. , 7. , 5.6])

In [ ]:
#x.shape[0]
len(y)

6

In [ ]:
cmp = x == y

In [ ]:
cmp

array([ True, False, False, False, False,  True])

In [ ]:
cmp.sum()

2

In [ ]:
if(cmp.sum() == len(x)):
  print('Os vetores são iguais')
else:
  print('Os vetores são diferentes')

Os vetores são diferentes


In [ ]:
Z1 = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])
Z2 = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])

In [ ]:
cmp2 = Z1 == Z2

In [ ]:
cmp2

array([ True,  True,  True,  True,  True,  True])

In [ ]:
if(cmp2.sum() == len(Z1)):
  print('Os vetores são iguais')
else:
  print('Os vetores são diferentes')

Os vetores são iguais


In [ ]:
# Slicing Saltando Valores 1D

In [ ]:
m = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
m[0:10:3]  # start:end:step