## Curso NumPy  - Aula 07 - Manipulando Vetores 2D

Intrutor: Rafael F.V.C. Santos

Canal YouTube: https://bit.ly/CanalYouTube-Analistas-Quant 

Curso Python Fundamentos (Grátis): http://bit.ly/python-fundamentos

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.21.6'

In [ ]:
# Geração de Números aleatórios

In [ ]:
np.random.seed(777)

In [ ]:
x = np.random.randint(100, size=(3,3))

In [ ]:
x

array([[47, 59, 38],
       [87, 49, 71],
       [29, 39, 89]])

In [ ]:
x1 = np.random.randint(5, size=(3,3))

In [ ]:
x1

array([[2, 0, 2],
       [0, 3, 1],
       [2, 4, 1]])

In [ ]:
x2 = np.random.randint(2, size=(10,10))

In [ ]:
x2

array([[1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 0, 1, 1, 0, 1],
       [0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 1]])

In [ ]:
# Como filtrar posições de valores 

In [ ]:
x

array([[47, 59, 38],
       [87, 49, 71],
       [29, 39, 89]])

In [ ]:
r, c = np.where( x >= 5 & x <= 30  )

ValueError: ignored

In [ ]:
r, c = np.where( (x >= 5) & (x <= 50)  )

In [ ]:
r

array([0, 0, 1, 2, 2])

In [ ]:
c

array([0, 2, 1, 0, 1])

In [ ]:
valores = x[r,c]

In [ ]:
valores

array([47, 38, 49, 29, 39])

In [ ]:
# Organizando em Tuplas os Índices

In [ ]:
i = list(zip(r,c))

In [ ]:
i

[(0, 0), (0, 2), (1, 1), (2, 0), (2, 1)]

In [ ]:
k = [x[j] for j in i]

In [ ]:
k

[47, 38, 49, 29, 39]

In [ ]:
# Filtros substituindo valores

In [ ]:
a = np.where( (x >= 5) & (x <= 50), x, 0 )

In [ ]:
a

array([[47,  0, 38],
       [ 0, 49,  0],
       [29, 39,  0]])

In [ ]:
a1 = np.where( (x >= 5) & (x <= 50), x, 88 )

In [ ]:
a1

array([[47, 88, 38],
       [88, 49, 88],
       [29, 39, 88]])

In [ ]:
a2 = np.where( ~((x >= 5) & (x <= 50)), x, 0 )

In [ ]:
a2

array([[ 0, 59,  0],
       [87,  0, 71],
       [ 0,  0, 89]])

In [ ]:
# Modificando valores de submatrizes

In [ ]:
x

array([[47, 59, 38],
       [87, 49, 71],
       [29, 39, 89]])

In [ ]:
x[0,0] = 100

In [ ]:
x

array([[100,  59,  38],
       [ 87,  49,  71],
       [ 29,  39,  89]])

In [ ]:
a2

array([[ 0, 59,  0],
       [87,  0, 71],
       [ 0,  0, 89]])

In [ ]:
x[1:3,0] = 9,99

In [ ]:
x

array([[100,  59,  38],
       [  9,  49,  71],
       [ 99,  39,  89]])

In [ ]:
a2

array([[ 0, 59,  0],
       [87,  0, 71],
       [ 0,  0, 89]])

## Técnicas avançadas de Manipulação de Arrays 2D

In [ ]:
np.random.seed(2)

In [ ]:
x = np.random.rand(3, 3); x

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [ ]:
y = x.copy() + 1; y

array([[1.4359949 , 1.02592623, 1.54966248],
       [1.43532239, 1.4203678 , 1.33033482],
       [1.20464863, 1.61927097, 1.29965467]])

In [ ]:
z = y[:,2].copy(); z

array([1.54966248, 1.33033482, 1.29965467])

In [ ]:
# Empilha verticalmente

np.vstack([z,z,z,z])

array([[1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467]])

In [ ]:
np.array([z,z,z,z])

array([[1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467]])

In [ ]:
# Função np.reshape e np.hstack

In [ ]:
z.T

array([1.20464863, 1.61927097, 1.29965467])

In [ ]:
z1 = np.reshape(z, (3,1) ); z1

array([[1.20464863],
       [1.61927097],
       [1.29965467]])

In [ ]:
# Empilha horizontalmente

In [ ]:
np.hstack([z1,z1,z1,z1])

array([[1.20464863, 1.20464863, 1.20464863, 1.20464863],
       [1.61927097, 1.61927097, 1.61927097, 1.61927097],
       [1.29965467, 1.29965467, 1.29965467, 1.29965467]])

In [ ]:
# Transformar matriz em Vetor

In [ ]:
x

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [ ]:
x.size

9

In [ ]:
xf = np.reshape(x, 9)

In [ ]:
xf

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467])

In [ ]:
np.reshape(x, (1,9))

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
        0.33033482, 0.20464863, 0.61927097, 0.29965467]])

In [ ]:
np.reshape(x, x.size)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467])

In [ ]:
# Split de vetores

In [ ]:
v = np.arange(12) + 1; v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
v1, v2 = np.split(v, [3])

In [ ]:
v1

array([1, 2, 3])

In [ ]:
v2

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Cuidado

v_1, v_2, v_3 = np.split(v, 3)

In [ ]:
v_1

array([1, 2, 3, 4])

In [ ]:
v_2

array([5, 6, 7, 8])

In [ ]:
v_3

array([ 9, 10, 11, 12])

In [ ]:
w1,w2 = np.split(v, 2)

In [ ]:
w2

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
w_1,w_2 = np.split(v, [2])

In [ ]:
w_1

array([1, 2])

In [ ]:
w_2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Split de Matrizes 

In [ ]:
k = np.arange(24).reshape(4,6); k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
k1, k2, k3 = np.hsplit(k, [2,4])

In [ ]:
k1

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]])

In [ ]:
k2

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

In [ ]:
k3

array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])

In [ ]:
# Split Vertical de Matrizes

In [ ]:
k


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
kv1, kv2 = np.vsplit(k, [2])

In [ ]:
kv1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
kv2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
kv_1, kv_2,kv_3,kv_4 = np.vsplit(k, 4)

In [ ]:
kv_1

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
kv_2

array([[ 6,  7,  8,  9, 10, 11]])

In [ ]:
kv_3

array([[12, 13, 14, 15, 16, 17]])

In [ ]:
kv_4

array([[18, 19, 20, 21, 22, 23]])

In [ ]:
# Concatenando Vetores

In [ ]:
c = np.array([1,2,4,7,8,9])

In [ ]:
c

array([1, 2, 4, 7, 8, 9])

In [ ]:
np.concatenate([c,c])

array([1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9])

In [ ]:
np.concatenate([np.sqrt(c),c*2])

array([ 1.        ,  1.41421356,  2.        ,  2.64575131,  2.82842712,
        3.        ,  2.        ,  4.        ,  8.        , 14.        ,
       16.        , 18.        ])

In [ ]:
np.tile(c,10)

array([1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7,
       8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2,
       4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9])

In [ ]:
# Matrizes

np.concatenate([k3,k3,k2],axis=1)

array([[ 4,  5,  4,  5,  2,  3],
       [10, 11, 10, 11,  8,  9],
       [16, 17, 16, 17, 14, 15],
       [22, 23, 22, 23, 20, 21]])

In [ ]:
np.tile(k3,10)

array([[ 4,  5,  4,  5,  4,  5,  4,  5,  4,  5,  4,  5,  4,  5,  4,  5,
         4,  5,  4,  5],
       [10, 11, 10, 11, 10, 11, 10, 11, 10, 11, 10, 11, 10, 11, 10, 11,
        10, 11, 10, 11],
       [16, 17, 16, 17, 16, 17, 16, 17, 16, 17, 16, 17, 16, 17, 16, 17,
        16, 17, 16, 17],
       [22, 23, 22, 23, 22, 23, 22, 23, 22, 23, 22, 23, 22, 23, 22, 23,
        22, 23, 22, 23]])