## Curso NumPy  - Aula 05 - Vetores 2D

Intrutor: Rafael F.V.C. Santos

Canal YouTube: https://bit.ly/CanalYouTube-Analistas-Quant 

Curso Python Fundamentos (Grátis): http://bit.ly/python-fundamentos

In [1]:
import numpy as np

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

In [ ]:
# Vetor 2D
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [ ]:
# Modificando Valores de Matrizes

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
y = x.T

In [ ]:
y

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [ ]:
y[2,1] = 77

In [ ]:
y

array([[ 1,  4],
       [ 2,  5],
       [ 3, 77]], dtype=int32)

In [ ]:
x

array([[ 1,  2,  3],
       [ 4,  5, 77]], dtype=int32)

In [ ]:
y2 = x.copy().T

In [ ]:
y2

array([[ 1,  4],
       [ 2,  5],
       [ 3, 77]], dtype=int32)

In [ ]:
y2[0,0]  = 888

In [ ]:
y2

array([[888,   4],
       [  2,   5],
       [  3,  77]], dtype=int32)

In [ ]:
x

array([[ 1,  2,  3],
       [ 4,  5, 77]], dtype=int32)

In [ ]:
# Fatiamento de Vetores 2D 

In [ ]:
for i in range(2,7):
  print(i)

2
3
4
5
6


In [ ]:
[range(1-1,i+4) for i in [1,2,3,4]]

[range(0, 5), range(0, 6), range(0, 7), range(0, 8)]

In [ ]:
x1 = np.array([range(i-1,i+4) for i in [1,2,3,4]])  # analistas quant - list comprehension

In [ ]:
x1

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
x1.shape

(4, 5)

In [ ]:
# Coletando linha
l2 = x1[1,:]

In [ ]:
l2

array([1, 2, 3, 4, 5])

In [ ]:
# Coletando coluna
c4 = x1[:,3]

In [ ]:
c4

array([3, 4, 5, 6])

In [ ]:
sm = x1[2:,3:]

In [ ]:
sm

array([[5, 6],
       [6, 7]])

In [ ]:
# Fatiamento de submatriz

In [ ]:
sm2 = x1[1:3,1:3]

In [ ]:
sm2

array([[2, 3],
       [3, 4]])

In [ ]:
# Exercícios:

x1

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [9]:
M1 = x1[1:3,1:3]

M2 = x1[0:2,2:4]

M3 = x1[:3,3:]  # Atenção!

In [10]:
M3

array([[3, 4],
       [4, 5],
       [5, 6]])

In [11]:
# Arrays 2D Especiais

In [21]:
np.empty((5,3))

array([[1.42130275e-316, 1.06099790e-312, 1.01855798e-312],
       [9.54898106e-313, 1.08221785e-312, 1.03977794e-312],
       [1.23075756e-312, 1.14587773e-312, 1.12465777e-312],
       [9.76118064e-313, 1.14587773e-312, 1.01855798e-312],
       [1.20953760e-312, 5.22286780e-143, 2.66023306e-312]])

In [22]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# Matriz identidade
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
# Matrizes Importantes - Álgebra

In [34]:
xd = np.diagflat([[1,4,7,-9, 8]])

In [35]:
xd

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  7,  0,  0],
       [ 0,  0,  0, -9,  0],
       [ 0,  0,  0,  0,  8]])

In [36]:
d = np.diag(xd)

In [37]:
d

array([ 1,  4,  7, -9,  8])

In [ ]:
# Soma os elementos da diagonal principal - Traço 

In [38]:
trace = np.trace(xd)

In [39]:
trace

11

In [ ]:
# Matriz de Vandermonde

In [40]:
a = np.array([1,2,3,4,5])

n = 5

v = np.vander(a,n)

In [41]:
v

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [ ]:
# Como copiar submatrizes - Atenção

In [42]:
y1 = v[0:2, 3:5]

In [43]:
y1

array([[1, 1],
       [2, 1]])

In [44]:
y2 = v[3:5, 0:2]

In [45]:
y2

array([[256,  64],
       [625, 125]])

In [46]:
y2 = y2.T

In [47]:
y2

array([[256, 625],
       [ 64, 125]])

In [48]:
v

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [49]:
v[0:2, 3:5] = y1

In [50]:
v

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [52]:
v[3:5, 0:2] = y2

In [53]:
v

array([[  1,   1,   1, 256, 625],
       [ 16,   8,   4,  64, 125],
       [ 81,  27,   9,   3,   1],
       [256, 625,  16,   4,   1],
       [ 64, 125,  25,   5,   1]])

In [54]:
y3 = v[3:5, 0:2].copy()

y4 = v[0:2, 3:5].copy()