## Curso NumPy  - Aula 04 - Lidando com Inf

Intrutor: Rafael F.V.C. Santos

Canal YouTube: https://bit.ly/CanalYouTube-Analistas-Quant 

Curso Python Fundamentos (Grátis): http://bit.ly/python-fundamentos

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,0,4,5])

In [ ]:
r = a/b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
r

array([ 1.,  1., inf,  1.,  1.])

In [ ]:
r.sum()

inf

In [ ]:
# Como remover inf de um vetor

In [ ]:
i = np.where(r == np.inf)

In [ ]:
r[i]

array([inf])

In [ ]:
def remove_inf(x):
  pi = np.where(x == np.inf)
  i = np.where(x != np.inf)
  return x[i]


In [ ]:
remove_inf(r)

array([1., 1., 1., 1.])

In [ ]:
r

array([ 1.,  1., inf,  1.,  1.])

In [ ]:
np.asarray_chkfinite(r)

ValueError: ignored

In [ ]:
try:
  np.asarray_chkfinite(r)
except ValueError:
  rm = remove_inf(r)

In [ ]:
rm

array([1., 1., 1., 1.])

In [ ]:
# Função que remove inf e diz posição

In [ ]:
def remove_inf_pos(x):
  pi = np.where(x == np.inf)
  i = np.where(x != np.inf)
  return x[i],pi

In [ ]:
a1 = np.array([1,2,3,4,5,6,7,8,9])
a2 = np.array([1,0,3,0,5,6,0,8,0])

In [ ]:
c1 = a1/a2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
c1

array([ 1., inf,  1., inf,  1.,  1., inf,  1., inf])

In [ ]:
c1m, pinf = remove_inf_pos(c1)

In [ ]:
c1m

array([1., 1., 1., 1., 1.])

In [ ]:
pinf[0]

array([1, 3, 6, 8])

In [ ]:
pinf

(array([1, 3, 6, 8]),)

In [ ]:
c1[pinf]

array([inf, inf, inf, inf])

In [ ]:
c1[pinf[0]]

array([inf, inf, inf, inf])

In [ ]:
# Vetores espaçados linearmente e em escala logarítmica

In [ ]:
x = np.linspace(0,50,num=100)

In [ ]:
x

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

In [ ]:
# escala logarítmica

In [ ]:
y = np.logspace(1,4, num=4, base=10)

In [ ]:
y

array([   10.,   100.,  1000., 10000.])

## Clonando Arrays

In [2]:
x = np.array([.2, -2.5, 3.43, 5.7, -0.03, 3.7], np.float128)

In [3]:
h = np.empty_like(x)

In [4]:
h

array([0., 0., 0., 0., 0., 0.], dtype=float128)

In [5]:
u = np.zeros_like(x)

In [6]:
u

array([0., 0., 0., 0., 0., 0.], dtype=float128)

In [7]:
k = np.ones_like(x)

In [8]:
k

array([1., 1., 1., 1., 1., 1.], dtype=float128)