## Curso NumPy  - Exercício 01

Intrutor: Rafael F.V.C. Santos

Canal YouTube: https://bit.ly/CanalYouTube-Analistas-Quant 

Curso Python Fundamentos (Grátis): http://bit.ly/python-fundamentos 

# Exercício 01 - Avaliar igualdade de vetores e seus elementos

- A partir de dois vetores: x e y;

- Construir uma função/algoritmo para avaliar se dois vetores são iguais ou diferentes; 

- Apresentar os elementos iguais dos vetores;  

- Comparar elemento por elemento dos vetores apresentar índices onde os valores são iguais nos dois vetores.


In [1]:
import numpy as np

In [24]:
x = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])
y = np.array([1. , 2.6 , 3., 4. , 7. , 5.6])

In [17]:
x = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])
y = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])

In [13]:
x = np.array([1.5, 3. , 2.6, 43.3, 73.7, 5.36])
y = np.array([1.0, 3.3 , 2.36, 4.3, 7.73, 5.6])

In [14]:
cmp = x == y

In [ ]:
# Dicas para resolver o exercício 01

In [8]:
cmp.all()

True

In [15]:
cmp.any()

False

In [22]:
np.where(x==y)

(array([0, 5]),)

## Solução do Exercício 01

In [ ]:
x = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])
y = np.array([1. , 2.6 , 3., 4. , 7. , 5.6])

In [25]:
cmp = x==y

In [26]:
cmp

array([ True, False, False, False, False,  True])

In [27]:
i = 0

if(cmp.all()):
  print('Todos os elementos são iguais!')
elif(cmp.any()):
  print('Alguns elementos são iguais, são eles:')
  for e in cmp:
    if(e):
      print('%.1f'% y[i])
    i += 1 # i = i + 1
  
  print('-------------')
  for e in x:
    j = np.where(e == y) # indexação de igual
    print(j)
    if(j[0].size != 0):
      print(y[j])
else:
  print('Todos os elementos são diferentes.')

Alguns elementos são iguais, são eles:
1.0
5.6
-------------
(array([0]),)
[1.]
(array([2]),)
[3.]
(array([1]),)
[2.6]
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([5]),)
[5.6]
